version: '3'

services:
  hyperf-crud:
    container_name: hyperf-crud
    platform: linux/amd64
    image: hyperf/hyperf:8.3-alpine-v3.19-swoole-slim
    volumes:
      - ./:/data/project
    command: ["tail","-f","/dev/null"]
    working_dir: /data/project
    ports:
      - 9501:9501
